### ISSUE TITLE
Animate panel/radios light knob

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#728]
I don't think this knob is animated.
![lightswitch](https://cloud.githubusercontent.com/assets/11069680/13695683/a47af668-e726-11e5-8f5b-875f61cc5499.jpg)

**Comment by gilbertohasnofb** [comment]
Yes, that's correct. And there is also one more issue with this knob: in RL, if you turn the black part (the exterior of the knob), you control the light of the panel. If you turn the inner part of the knob (the silver part) you control the light of the radio. Currently our knob just sets both lightning levels at once.

**Comment by gilbertohasnofb** [comment]
If I am not mistaken, the c182 already has this behaviour I described above implemented, in case anyone wants to see how it works.

**Comment by gilbertohasnofb** [comment]
One more thing, I realized that the label PANEL LT and RADIO LT aren't completely correct: they are missing a circle before them, and the knob also has an arrow label indicating the direction in which the brightness increments. I started fixing this on branch `bug-728`, and I will do this for all panel liveries:

**Comment by gilbertohasnofb** [comment]
Ok, I fixed all labels and pushed it.

**Comment by wlbragg** [comment]
Nice, I can do the animation in the next couple days.

**Comment by wlbragg** [comment]
I was getting ready to animate this knob but have a couple questions. I looked at the 182 and it isn't animated either.
The 182 knobs only have one action each VS a double knob.
My question is how does the knob actually work. Does the front portion (silver part) pop in and out so you can turn it or is suppose to be long enough by default to be able to grip and turn?

**Comment by algefaen** [comment]
Excerpts from wlbragg's message of 2016-03-30 16:42:18 +0200:
> My question is how does the knob actually work. Does the front portion
> (silver part) pop in and out so you can turn it or is suppose to be long
> enough by default to be able to grip and turn?

https://youtu.be/Ln4aTIq6Nps?t=3m43s

-- 
alge

**Comment by wlbragg** [comment]
Thanks, but that still isn't enough. Our c172p has only the top knob and it looks the same as that one as far as the legend. It looks like a duel option knob. But I can't tell by the video it the silver part of the knob pops in and out to be able to grip it or is just extruded at all time. Because I'm guessing the knob can be tuned by the silver part "panel" and black part "radio". Does the silver part pop in an out?

**Comment by algefaen** [comment]
Yeah, sorry, I just read the email and thought the video answered it, but I see from the images that it doesn't. I'll see if our 172s have the same nobs and grab some video if they do within a couple of days. My guess from just looking at pictures is that you have to hold in the silver part and turn the whole nob for radio lights.

**Comment by gilbertohasnofb** [comment]
> The 182 knobs only have one action each VS a double knob.

I don't think that's correct, I am quite sure they are double knobs. The mouse cursor will be either :left_right_arrow: or :arrow_up_down:. The thing is the panel lightning is not implemented yet, so it may look like the knobs are just single action.

As for the knob in our plane, I am quite sure it is supposed to be identical to the one in the video @algefaen posted above. See this photo by @tigert:

![aad](https://cloud.githubusercontent.com/assets/5700795/14157273/936cd91e-f6ca-11e5-940f-e1da27ce545d.jpg)

And so, what I understand is that it works as follows: the silver part can be rotated independently of the black part, so turning one changes the lightning of the radio only, turning the other changes the lightning of the other instruments.

**Comment by wlbragg** [comment]
OK, but the silver part doesn't look like it sticks out enough to grab, so I was wondering if it is like one of those buttons that click in an out. When in you cant turn it and when out you can.

**Comment by gilbertohasnofb** [comment]
> but the silver part doesn't look like it sticks out enough to grab

Really? To me it looks like it sticks out enough both on the video and on the image above. Maybe @tigert or @Juanvvc can confirm this, but I don't think you need to click it out before turning or anything fancy like that.

**Comment by gilbertohasnofb** [comment]
One more image:

![](https://i.ytimg.com/vi/IP2PIjqf-Wc/maxresdefault.jpg)

**Comment by wlbragg** [comment]
What is the "ALT STATIC AIR"?

**Comment by gilbertohasnofb** [comment]
It's a toggle that activates an alternate static source, but I don't know exactly how it works. But if you look on the images above you'll see it's a knob that looks like the light knob, but half the size and places to its right.

**Comment by onox** [comment]
AFAIK it's an alternate way to get the static pressure using the air in the cabin instead of the outside air. It can be used if the static port outside is blocked somehow, but it changes slower.

**Comment by wlbragg** [comment]
If I model it are we going to right a system for it?

**Comment by gilbertohasnofb** [comment]
I suppose so. I will open an issue for that.

**Comment by Juanvvc** [comment]
I really can't remember how the panel/radios light knob works. I don't think I ever used that knob :) According to the POH, it is a dual knob with an inner ring (radios) and an outer ring (panel). No push/pull to activate the inner knob.

The alternate air intake takes the static pressure from the cabin, as onox says. It is used when the pitot tube is blocked, normally due to icing. The alternate air intake uses the cabin air as static pressure, and this air is usually much warmer (i.e.: less dense) than the external air. This means readings will be skewed: the altimeter will show an altitude higher than real, for example. In some cases, there is not any alternate intake valve and you must  break the glass of the VSI. Check: http://www.aviationgroundschool.com/sample_pages/airspeed3.html and http://studentpilot.com/interact/forum/archive/index.php/t-37253.html

**Comment by gilbertohasnofb** [comment]
@Juanvvc Thanks for the info, I copied what you posted over to the issue 741.

**Comment by algefaen** [comment]
grabbed a video, hope it's not too late: https://goo.gl/photos/rApgjAdzfuSsEUcw6

**Comment by algefaen** [comment]
(that's a 172N, but it looks like it's the same as we have.)

**Comment by gilbertohasnofb** [comment]
@wlbragg what about we just work on the model and textures on this branch here for both knobs (lights and static source), and then later implement the static source functionality using this branch here https://github.com/Juanvvc/c172p-detailed/issues/741 ?

**Comment by wlbragg** [comment]
:+1:

**Comment by onox** [comment]
Almost got this working. Will push in an hour.

**Comment by gilbertohasnofb** [comment]
Yay! :+1:
