### ISSUE TITLE
Pitot cover set systems/pitot/servicable to false?

### ISSUE THREAD

**Issue by dg-505** [Juanvvc/c172p-detailed#781]
Hi,

this is a small suggestion for an enhancement.
In it's current configuration the pitot-cover-visible sets the property `/instrumentation/airspeed-indicator/indicated-speed-kt` to 0.0. (See lines 7202-7232 in c172p/Models/c172p.xml)

To be honest I think that's not very realistic, because in reality, when the pitot tube is blocked, the ASI will indicate accelerating durinc climb, and it indicates decelerating during descent.

The situation is the same when the pitot cover is not removed, or when it's blocked e.g. by ice, insects, etc.

To simulate this behaviour realistically, I would suggest that the command

```
<animation>
        <type>pick</type>
        <object-name>PitotTube</object-name>
        <action>
            <button>0</button>
            <repeatable>false</repeatable>
            <binding>
                <condition>
                    <property>/sim/model/c172p/securing/pitot-cover-addable</property>
                </condition>
                <command>property-assign</command>
                <property alias="/params/securing/pitot-cover"/>
                <value>true</value>
            </binding>
            <binding>
                <command>property-assign</command>
                <property>/instrumentation/airspeed-indicator/indicated-speed-kt</property>
                <value>0.0</value>
            </binding>
        </action>
        [...]
    </binding>
```

set's the property `systems/pitot/servicable` to `false`.

What do you think?

Cheers
Jonathan

**Comment by algefaen** [comment]
To simulate this behaviour realistically, won't we have to implement a proper pitot static system which simulates all the [pitot static errors](https://en.wikipedia.org/wiki/Pitot-static_system#Pitot-static_errors)? There's some pretty fun things happening in that system, for example if you fly straight and level and pull on the yoke, the VSI can indicate negative climb a fraction of a second before it starts showing the climb. The direct coupling (no damping) between simulator variables and our gauges is something that we could become better at in general.

Setting the pitot to unserviceable instead of the ASI directly might be a good step in the right direction though. (=

**Comment by wkitty42** [comment]
On 06/06/2016 10:21 AM, algefaen wrote:
> Setting the pitot to unserviceable instead of the ASI directly might be a
> good step in the right direction though. (=

we just removed a line that set serviceable to false because there wasn't 
anything else that ever set it to true... effectively a bug because the ASI 
didn't work unless you manually went and set the property to true...

ow, neuron! yeah, ok... the line wasn't removed but changed to force true to 
ensure the device works and repair the bug in those craft already flown with the 
ASI not working... the line that was removed was the one saving the property in 
the aircraft-data/c172p.xml file with the other saved properties... we may 
actually be waiting to merge that bug fix, too...

personally, i don't have a problem putting the line back in with another, 
opposite, one if the pitot cover is in place during startup... then also tying 
it into the pitot cover code so that the property is also flipped as needed there...

i don't know anything about the rest of that system, though... how ever you guys 
want to handle it to make it more accurate is fine with me ;)

**Comment by dg-505** [comment]
IMHO for failure modes it would be enough if we could implement somenthing like the follwing table, as this isn't a pitot tube simulator (like @gilbertohasnofb said once) :wink: 

| Instrument |                  Blocked static port                  |                   Blocked pitot tube                  | Both blocked           |
|:----------:|:-----------------------------------------------------:|:-----------------------------------------------------:|------------------------|
|    Vario   |                       Fixed at 0                      |                   Normal indication                   | Fixed at 0             |   |
|  Altimeter |                 Fixed at current value                |                   Normal indication                   | Fixed at current value |
|     ASI    | Climb: Indicates too slow Descent: Indicates too fast | Climb: Indicates too fast Descent: Indicates too slow | Fixed at current value |

At least I think for a generic failure simulation this is enough. And it probably could be included into other planes quite easily.

**Comment by onox** [comment]
The pitot tube system is already set to enabled/disabled in `Systems/indicated-airspeed.xml` (lines 84 to 91)

I'm not sure why that second `<binding>` in `Models/c172p.xml` still exists though. Maybe we didn't see it.

**Comment by dg-505** [comment]
Okay, after some testing I see that the indications of ASI, Altimeter and Varion are indeed correct :+1:
